<template>
  <v-btn @click="generatePlaces" block>Generate Places</v-btn>
</template>

<script>
import firebase from "@/firebase";
import * as fb from "@/firebase";

export default {
  name: "generate-places",
  data() {
    return {
      starterPlaces: [
        {
          address: {
            country: "US",
            county: "Warren County",
            locality: "Springboro",
            plus_code: "HQ54+HV Springboro, OH, USA",
            postal_code: "45066",
            route: "W Central Ave",
            state: "Ohio",
            street_number: "305",
          },
          createdOn: new Date(),
          doc_id: "0I2uk2CvNYJeCC6XPSJX",
          formatted_address: "305 W Central Ave, Springboro, OH 45066, USA",
          location: { lat: 39.5589533, lng: -84.2428284 },
          name: "The Donut Haus Bakery",
          place_id: "ChIJaQrIcVuKQIgRr82jS6YLZr8",
          ratings: {
            compliance: 0,
            enforcement: 0,
            general: 0,
            notifications: 0,
            total: 0,
          },
          types: ["bakery"],
        },
        {
          address: {
            country: "US",
            county: "Warren County",
            locality: "Springboro",
            plus_code: "HQJ9+49 Springboro, OH, USA",
            postal_code: "45066",
            route: "Main St",
            state: "Ohio",
            street_number: "825",
            township: "Clearcreek Township",
          },
          createdOn: new Date(),
          doc_id: "11Zy7mlxKr2Qu5KSG8x3",
          formatted_address: "825 Main St, Springboro, OH 45066, USA",
          location: { lat: 39.58028669999999, lng: -84.2315589 },
          name: "Kettering Health Network: Springboro Health Center",
          place_id: "ChIJM1JtabKLQIgRj-bjK4lEaWA",
          ratings: {
            compliance: 0,
            enforcement: 0,
            general: 0,
            notifications: 0,
            total: 0,
          },
          types: ["hospital"],
        },
        {
          address: {
            country: "US",
            county: "Montgomery County",
            locality: "Miamisburg",
            plus_code: "HQX9+RX Miamisburg, OH, USA",
            postal_code: "45342",
            route: "Innovation Drive",
            state: "Ohio",
            street_number: "10800",
            township: "Miami Township",
          },
          createdOn: new Date(),
          doc_id: "17mAYOtRWi146YgzTmS1",
          formatted_address:
            "10800 Innovation Drive, Miamisburg, OH 45342, USA",
          location: { lat: 39.59954939999999, lng: -84.23002009999999 },
          name: "Kohl's",
          place_id: "ChIJvX0Eys-JQIgR5O72GNEVH9Q",
          ratings: {
            compliance: 0,
            enforcement: 0,
            general: 0,
            notifications: 0,
            total: 0,
          },
          types: ["department_store"],
        },
        {
          address: {
            country: "US",
            county: "Montgomery County",
            locality: "Miamisburg",
            plus_code: "JQ7F+R7 Miamisburg, OH, USA",
            postal_code: "45342",
            route: "N Springboro Pike",
            state: "Ohio",
            street_number: "9400",
            township: "Miami Township",
          },
          createdOn: new Date(),
          doc_id: "1uuSdrvfpBNyXDTt94eD",
          formatted_address:
            "9400 N Springboro Pike, Miamisburg, OH 45342, USA",
          location: { lat: 39.6146038, lng: -84.2268426 },
          name: "Roosters",
          place_id: "ChIJi-rv-_iIQIgR7xgcvDGPoAs",
          ratings: {
            compliance: 0,
            enforcement: 0,
            general: 0,
            notifications: 0,
            total: 0,
          },
          types: ["bar", "restaurant"],
        },
        {
          address: {
            country: "US",
            county: "Warren County",
            locality: "Springboro",
            plus_code: "HQ55+4H Springboro, OH, USA",
            postal_code: "45066",
            route: "W Central Ave",
            state: "Ohio",
            street_number: "263",
            township: "Clearcreek Township",
          },
          createdOn: new Date(),
          doc_id: "2FR10DRicwnuHZj5W9gH",
          formatted_address: "263 W Central Ave, Springboro, OH 45066, USA",
          location: { lat: 39.5578626, lng: -84.24101209999999 },
          name: "The Vet In Springboro",
          place_id: "ChIJvUBp-1qKQIgRN5_eQzLWtNY",
          ratings: {
            compliance: 0,
            enforcement: 0,
            general: 0,
            notifications: 0,
            total: 0,
          },
          types: ["veterinary_care"],
        },
        {
          address: {
            country: "US",
            locality: "Port Angeles",
            plus_code: "R92W+R7 Port Angeles, WA, USA",
            postal_code: "98362",
            route: "Mt Angeles Rd",
            state: "Washington",
            street_number: "3002",
          },
          createdOn: new Date(),
          doc_id: "2wJWbBCjEVWjakgqdEK5",
          formatted_address: "3002 Mt Angeles Rd, Port Angeles, WA 98362, USA",
          location: { lat: 47.8021067, lng: -123.6043524 },
          name: "Olympic National Park",
          place_id: "ChIJ0XIEzwmAjlQRUXl9squHIAA",
          ratings: {
            compliance: 0,
            enforcement: 0,
            general: 0,
            notifications: 0,
            total: 0,
          },
          types: ["tourist_attraction", "park"],
        },
        {
          address: {
            country: "US",
            county: "Montgomery County",
            locality: "Kettering",
            plus_code: "MRQQ+65 Kettering, OH, USA",
            postal_code: "45429",
            route: "E Stroop Rd",
            state: "Ohio",
            street_number: "530",
          },
          createdOn: new Date(),
          doc_id: "35R6fGlI1gH0txgxRfAK",
          formatted_address: "530 E Stroop Rd, Kettering, OH 45429, USA",
          location: { lat: 39.68812200000001, lng: -84.16202109999999 },
          name: "Kroger Fresh Fare",
          place_id: "ChIJE8mAFJWFQIgRjUPWG-ST8-k",
          ratings: {
            compliance: 0,
            enforcement: 0,
            general: 0,
            notifications: 0,
            total: 0,
          },
          types: [],
        },
        {
          address: {
            country: "US",
            county: "Greene County",
            locality: "Beavercreek",
            plus_code: "MVVX+84 Beavercreek, OH, USA",
            postal_code: "45440",
            route: "Glengarry Dr",
            state: "Ohio",
            street_number: "4427",
            township: "Beavercreek Township",
          },
          createdOn: new Date(),
          doc_id: "3Pg7L4slTSvQB2Vvaum3",
          formatted_address:
            "4427 Glengarry Dr Space C - 122, Beavercreek, OH 45440, USA",
          location: { lat: 39.693321, lng: -84.102154 },
          name: "Eddie Bauer",
          place_id: "ChIJpdwUhTOFQIgRLuXt_Rrr2Nw",
          ratings: {
            compliance: 5,
            enforcement: 4,
            general: 5,
            notifications: 5,
            total: 1,
          },
          types: ["shoe_store", "clothing_store"],
          updatedOn: new Date(),
        },
        {
          address: {
            country: "US",
            county: "Montgomery County",
            locality: "Huber Heights",
            plus_code: "VVG5+7W Huber Heights, OH, USA",
            postal_code: "45424",
            route: "Troy Pike",
            state: "Ohio",
            street_number: "8301",
          },
          createdOn: new Date(),
          doc_id: "3jElcDVEK2XmEdxY2iS6",
          formatted_address: "8301 Troy Pike, Huber Heights, OH 45424, USA",
          location: { lat: 39.8756635, lng: -84.1401353 },
          name: "Kohl's",
          place_id: "ChIJJ9OKMgJ9P4gRNH60GsLIPpo",
          ratings: {
            compliance: 5,
            enforcement: 5,
            general: 5,
            notifications: 5,
            total: 1,
          },
          types: ["department_store"],
          updatedOn: new Date(),
        },
        {
          address: {
            country: "US",
            county: "Greene County",
            locality: "Beavercreek",
            plus_code: "MWWF+69 Beavercreek, OH, USA",
            postal_code: "45440",
            route: "Indian Ripple Rd",
            state: "Ohio",
            street_number: "3776",
            township: "Beavercreek Township",
          },
          createdOn: new Date(),
          doc_id: "6Uefh8rcQ1aepyIPjTzG",
          formatted_address:
            "3776 Indian Ripple Rd, Beavercreek, OH 45440, USA",
          location: { lat: 39.695506, lng: -84.0765862 },
          name: "Bern's Garden Center-Landscaping",
          place_id: "ChIJfUr3lOiaQIgRGaV4zhJmbfk",
          ratings: {
            compliance: 0,
            enforcement: 0,
            general: 0,
            notifications: 0,
            total: 0,
          },
          types: [],
        },
        {
          address: {
            country: "US",
            county: "Montgomery County",
            locality: "Dayton",
            plus_code: "RPWM+6Q Dayton, OH, USA",
            postal_code: "45415",
            route: "N Main St",
            state: "Ohio",
            street_number: "8321",
          },
          createdOn: new Date(),
          doc_id: "743yYmaz0RKX2G3bw0ld",
          formatted_address: "8321 N Main St, Dayton, OH 45415, USA",
          location: { lat: 39.845576, lng: -84.26556699999999 },
          name: "Boston Stoker Coffee Co.",
          place_id: "ChIJaUJYQfl_P4gRaJcubuSZkuY",
          ratings: {
            compliance: 0,
            enforcement: 0,
            general: 0,
            notifications: 0,
            total: 0,
          },
          types: ["bakery", "cafe"],
        },
        {
          address: {
            country: "US",
            county: "Pender County",
            locality: "Hampstead",
            plus_code: "FC2P+H5 Hampstead, NC, USA",
            postal_code: "28443",
            route: "NC-210",
            state: "North Carolina",
            street_number: "2765",
            township: "Topsail",
          },
          createdOn: new Date(),
          doc_id: "7HvPVIguCpgxgfwQdicy",
          formatted_address: "2765 NC-210 E, Hampstead, NC 28443, USA,",
          location: { lat: 34.451406, lng: -77.5645136 },
          name: "Publix Super Market at Arboretum at Surf City",
          place_id: "ChIJxy1WPgCZqYkRkeRpkzpTOFk",
          ratings: {
            compliance: 1,
            enforcement: 1,
            general: 2,
            notifications: 4,
            total: 1,
          },
          types: ["supermarket", "bakery", "liquor_store"],
          updatedOn: new Date(),
        },
        {
          address: {
            country: "US",
            county: "Pennington County",
            locality: "Rapid City",
            plus_code: "2QMJ+GJ Rapid City, SD, USA",
            postal_code: "57701",
            route: "Stumer Rd",
            state: "South Dakota",
            street_number: "100",
          },
          createdOn: new Date(),
          doc_id: "AzyXlD9tk7VBdwmxIqXS",
          formatted_address: "100 Stumer Rd, Rapid City, SD 57701, USA",
          location: { lat: 44.03380569999999, lng: -103.2183798 },
          name: "Walmart Supercenter",
          place_id: "ChIJBcgcNU1CfYcR3i78H4GdpK0",
          ratings: {
            compliance: 5,
            enforcement: 5,
            general: 5,
            notifications: 5,
            total: 2,
          },
          types: [
            "department_store",
            "supermarket",
            "electronics_store",
            "home_goods_store",
            "clothing_store",
          ],
          updatedOn: new Date(),
        },
        {
          address: {
            country: "US",
            county: "Warren County",
            locality: "Waynesville",
            plus_code: "GWM5+M3 Waynesville, OH, USA",
            postal_code: "45068",
            state: "Ohio",
            township: "Wayne Township" 
          },
          createdOn: new Date(),
          doc_id: "CSWVx5PShOAVWKT0VgvP",
          formatted_address: "Waynesville, OH 45068, USA",
          location: { lat: 39.5342238, lng: -84.09234320000002 },
          name: "Waynesville Elementary School",
          place_id: "ChIJbRocFoWSQIgRzo7fCWvX8UY",
          ratings: {
            compliance: 0,
            enforcement: 0,
            general: 0,
            notifications: 0,
            total: 0,
          },
          types: ["primary_school", "school"],
        },
        {
          address: {
            country: "US",
            county: "Warren County",
            locality: "Franklin",
            plus_code: "HP8C+GW Franklin, OH, USA",
            postal_code: "45005",
            route: "E 2nd St",
            state: "Ohio",
            street_number: "1275",
            township: "Franklin Township",
          },
          createdOn: new Date(),
          doc_id: "CsHnNGOCEXMEc8gl4WqQ",
          formatted_address: "1275 E 2nd St, Franklin, OH 45005, USA",
          location: { lat: 39.5662579, lng: -84.27773719999999 },
          name: "Walmart Supercenter",
          place_id: "ChIJE0gEqdthQIgRcrpG-2TQ2cI",
          ratings: {
            compliance: 1.375,
            enforcement: 1.0833333333333335,
            general: 1.375,
            notifications: 1.75,
            total: 4,
          },
          types: [
            "department_store",
            "supermarket",
            "electronics_store",
            "home_goods_store",
            "clothing_store",
          ],
          updatedOn: new Date(),
        },
        {
          address: {
            country: "US",
            county: "Montgomery County",
            locality: "Centerville",
            plus_code: "JR6Q+62 Centerville, OH, USA",
            postal_code: "45458",
            route: "S Main St",
            state: "Ohio",
            street_number: "1001",
            township: "Washington Township",
          },
          createdOn: new Date(),
          doc_id: "D8Uu9xmjI1XkWpacNgrC",
          formatted_address: "1001 S Main St, Centerville, OH 45458, USA",
          location: { lat: 39.61055590000001, lng: -84.1624331 },
          name: "I-Vape",
          place_id: "ChIJGWxv5eqOQIgRjBwJMhn74dI",
          ratings: {
            compliance: 4,
            enforcement: 2,
            general: 5,
            notifications: 2,
            total: 1,
          },
          types: [],
          updatedOn: new Date(),
        },
        {
          address: {
            country: "US",
            county: "Montgomery County",
            locality: "Dayton",
            plus_code: "WQ3H+27 Dayton, OH, USA",
            postal_code: "45377",
            route: "Terminal Dr",
            state: "Ohio",
            street_number: "3600",
          },
          createdOn: new Date(),
          doc_id: "D9HatxYNgM47t457zji1",
          formatted_address: "3600 Terminal Dr, Dayton, OH 45377, USA",
          location: { lat: 39.90252419999999, lng: -84.2217719 },
          name: "Dayton International Airport",
          place_id: "ChIJMaf8XOd-P4gRNQ8NLx2OFgs",
          ratings: {
            compliance: 0,
            enforcement: 0,
            general: 0,
            notifications: 0,
            total: 0,
          },
          types: ["airport"],
        },
        {
          address: {
            country: "US",
            county: "Warren County",
            locality: "Franklin",
            plus_code: "HP37+F6 Franklin, OH, USA",
            postal_code: "45005",
            route: "E 4th St",
            state: "Ohio",
            street_number: "750",
            township: "Franklin Township",
          },
          createdOn: new Date(),
          doc_id: "DNDaj3JzoRH6Iux98qLz",
          formatted_address: "750 E 4th St, Franklin, OH 45005, USA",
          location: { lat: 39.553742, lng: -84.2869221 },
          name: "Franklin High School",
          place_id: "ChIJLRBARsthQIgRz7UWd5xdUp0",
          ratings: {
            compliance: 0,
            enforcement: 0,
            general: 0,
            notifications: 0,
            total: 0,
          },
          types: ["secondary_school", "school"],
        },
        {
          address: {
            country: "US",
            county: "Montgomery County",
            locality: "Centerville",
            plus_code: "JRMR+PF Centerville, OH, USA",
            postal_code: "45459",
            route: "N Main St",
            state: "Ohio",
            street_number: "215",
            township: "Washington Township",
          },
          createdOn: new Date(),
          doc_id: "Digee0hcWpDf5RtdeBBh",
          formatted_address: "215 N Main St, Centerville, OH 45459, USA",
          location: { lat: 39.6343055, lng: -84.1588329 },
          name: "Boston Stoker Coffee Co.",
          place_id: "ChIJw8ta-BuPQIgRwySwpQc4HqQ",
          ratings: {
            compliance: 0,
            enforcement: 0,
            general: 0,
            notifications: 0,
            total: 0,
          },
          types: ["cafe", "bakery"],
        },
      ],
    };
  },
  methods: {
    generatePlaces() {
      this.starterPlaces.map((place) => {
        return fb.placesCollection.add(place);
      });
    },
  },
};
</script>
