<template>
  <v-btn @click="generateRegions" block>Generate Regions</v-btn>
</template>

<script>
import firebase from "@/firebase";
import * as fb from "@/firebase";

export default {
  name: "generate-regions",
  data() {
    return {
      starterRegions: [
        {
          address: {
            country: "US",
            county: "Montgomery County",
            locality: "Kettering",
            state: "Ohio",
            township: "Sugarcreek Township",
          },
          createdOn: new Date(),
          formatted_address: "Kettering, OH, USA",
          location: { lat: 39.68950359999999, lng: -84.1688274 },
          name: "Kettering",
          place_id: "ChIJ8SLXDKSFQIgRpnJQASMjVq8",
          types: ["locality", "political"],
        },
        {
          address: {
            country: "US",
            county: "Greene County",
            locality: "Beavercreek",
            state: "Ohio",
            township: "Beavercreek Township",
          },
          createdOn: new Date(),
          formatted_address: "Beavercreek, OH, USA",
          location: { lat: 39.7092262, lng: -84.06326849999999 },
          name: "Beavercreek",
          place_id: "ChIJB-LwKg6bQIgRgu8TwuZQd7o",
          types: ["locality", "political"],
        },
        {
          address: {
            country: "US",
            county: "Montgomery County",
            state: "Ohio",
          },
          createdOn: new Date(),
          formatted_address: "Montgomery County, OH, USA",
          location: { lat: 39.7620028, lng: -84.3542049 },
          name: "Montgomery County",
          place_id: "ChIJcc4RhY9iQIgRFxRmOJXb_kk",
          types: ["administrative_area_level_2", "political"],
        },
        {
          address: {
            country: "US",
            county: "Warren County",
            locality: "Springboro",
            state: "Ohio",
            township: "Clearcreek Township",
          },
          createdOn: new Date(),
          formatted_address: "Springboro, OH, USA",
          location: { lat: 39.5522815, lng: -84.2332718 },
          name: "Springboro",
          place_id: "ChIJHTQQ4CeJQIgRKiJzNdF2-04",
          types: ["locality", "political"],
        },
        {
          address: {
            country: "US",
            county: "Montgomery County",
            locality: "Huber Heights",
            state: "Ohio",
          },
          createdOn: new Date(),
          formatted_address: "Huber Heights, OH, USA",
          location: { lat: 39.843947, lng: -84.12466080000002 },
          name: "Huber Heights",
          place_id: "ChIJv4Ktljl9P4gRwDzoFx-gGgc",
          types: ["locality", "political"],
        },
        {
          address: {
            country: "US",
            county: "Montgomery County",
            locality: "Miamisburg",
            state: "Ohio",
            township: "Miami Township",
          },
          createdOn: new Date(),
          formatted_address: "Miamisburg, OH, USA",
          location: { lat: 39.6428362, lng: -84.2866083 },
          name: "Miamisburg",
          place_id: "ChIJjVJnuoBiQIgR9yJWFI8WWg4",
          types: ["locality", "political"],
        },
        {
          address: {
            country: "US",
            county: "Montgomery County",
            locality: "Centerville",
            state: "Ohio",
            township: "Washington Township",
          },
          createdOn: new Date(),
          formatted_address: "Centerville, OH, USA",
          location: { lat: 39.6283928, lng: -84.15938179999999 },
          name: "Centerville",
          place_id: "ChIJW2OqA9dYQIgRaIwsVS1hBbM",
          types: ["locality", "political"],
        },
        {
          address: {
            country: "US",
            county: "Warren County",
            locality: "Franklin",
            postal_code: "45005",
            state: "Ohio",
            township: "Franklin Township",
          },
          createdOn: new Date(),
          formatted_address: "Franklin, OH 45005, USA",
          location: { lat: 39.5589474, lng: -84.30410739999999 },
          name: "Franklin",
          place_id: "ChIJUW47rLJhQIgRn7z71tUJiYU",
          types: ["locality", "political"],
        },
        {
          address: { country: "US", county: "Warren County", state: "Ohio" },
          createdOn: new Date(),
          formatted_address: "Warren County, OH, USA",
          location: { lat: 39.4241422, lng: -84.1857115 },
          name: "Warren County",
          place_id: "ChIJQcLNcG76QIgR1Nznyf8frn8",
          types: ["administrative_area_level_2", "political"],
        },
        {
          address: {
            country: "US",
            locality: "Huber Heights",
            postal_code: "45424",
            state: "Ohio",
          },
          createdOn: new Date(),
          formatted_address: "Huber Heights, OH 45424, USA",
          location: { lat: 39.853124, lng: -84.1224036 },
          name: "45424",
          place_id: "ChIJrTNoYUV9P4gRwSQkfUqWFpA",
          types: ["postal_code"],
        },
        {
          address: {
            country: "US",
            county: "Pennington County",
            locality: "Rapid City",
            state: "South Dakota",
            township: "Central Pennington",
          },
          createdOn: new Date(),
          formatted_address: "Rapid City, SD, USA",
          location: { lat: 44.0805434, lng: -103.2310149 },
          name: "Rapid City",
          place_id: "ChIJ-6W7nqVCfYcRx7eTPlphccQ",
          types: ["locality", "political"],
        },
        {
          address: {
            country: "US",
            county: "Warren County",
            locality: "Lebanon",
            postal_code: "45036",
            state: "Ohio",
          },
          createdOn: new Date(),
          formatted_address: "Lebanon, OH 45036, USA",
          location: { lat: 39.4353373, lng: -84.2029922 },
          name: "Lebanon",
          place_id: "ChIJSU5wSCf0QIgRlDsilDNt6KU",
          types: ["locality", "political"],
        },
        {
          address: {
            country: "US",
            county: "Clallam County",
            locality: "Port Angeles",
            state: "Washington",
            township: "Juan de Fuca",
          },
          createdOn: new Date(),
          formatted_address: "Port Angeles, WA, USA",
          location: { lat: 48.118146, lng: -123.4307413 },
          name: "Port Angeles",
          place_id: "ChIJR-fnwAxSjlQR2aVPY4xhvF0",
          types: ["locality", "political"],
        },
        {
          address: {
            country: "US",
            county: "Hamilton County",
            locality: "Cincinnati",
            state: "Ohio",
          },
          createdOn: new Date(),
          formatted_address: "Cincinnati, OH, USA",
          location: { lat: 39.1031182, lng: -84.5120196 },
          name: "Cincinnati",
          place_id: "ChIJ-SE43rFRQIgRF5PA5It--2k",
          types: ["locality", "political"],
        },
        {
          address: {
            country: "US",
            county: "Pender County",
            locality: "Hampstead",
            state: "North Carolina",
            township: "Topsail",
          },
          createdOn: new Date(),
          formatted_address: "Hampstead, NC, USA",
          location: { lat: 34.3675936, lng: -77.71054819999999 },
          name: "Hampstead",
          place_id: "ChIJ1076Aa6RqYkReuJcW9RIrhE",
          types: ["locality", "political"],
        },
        {
          address: {
            country: "US",
            county: "Butler County",
            locality: "Middletown",
            state: "Ohio",
          },
          createdOn: new Date(),
          formatted_address: "Middletown, OH, USA",
          location: { lat: 39.5150576, lng: -84.39827629999999 },
          name: "Middletown",
          place_id: "ChIJewQnqORdQIgRIAbP-R2gGgc",
          types: ["locality", "political"],
        },
        {
          address: {
            country: "US",
            county: "Montgomery County",
            locality: "Dayton",
            state: "Ohio",
            township: "Jefferson Township",
          },
          createdOn: new Date(),
          formatted_address: "Dayton, OH, USA",
          location: { lat: 39.7589478, lng: -84.1916069 },
          name: "Dayton",
          place_id: "ChIJAxTdrtWAQIgR5EwO8pLjQKY",
          types: ["locality", "political"],
        },
        {
          address: {
            country: "US",
            county: "Pender County",
            locality: "Surf City",
            state: "North Carolina",
            township: "Topsail",
          },
          createdOn: new Date(),
          formatted_address: "Surf City, NC, USA",
          location: { lat: 34.4271121, lng: -77.5460805 },
          name: "Surf City",
          place_id: "ChIJkcHh-5YIqYkRWS6i4_-W5Wg",
          types: ["locality", "political"],
        },
      ],
    };
  },
  methods: {
    generateRegions() {
      this.starterRegions.map((region) => {
        return fb.regionsCollection.add(region);
      });
    },
  },
};
</script>
